### ISSUE TITLE
Error Updating existing API

### ISSUE THREAD

**Issue by akashp1196** [SmartBear/swaggerhub-cli#125]
Hello,

I've set my base URL and API_KEY as instructed and then attempted to both update an existing API on our SwaggerHub as well as create a new API via the command line interface. Both resulted in the same error. My URL is correct and when I click on it does lead me to the HubTest/1.0.0 page where I can edit my API from swaggerhub.

`swaggerhub api:update myusername/HubTest/1.0.1 --file generated/swagger-ui/swagger.json --visibility public`

 ›   Error: request to https://ideas-swaggerhub.myorg.com/apis/apatel/HubTest/1.0.1 failed, reason: unable to verify the first certificate

I'm not sure how to resolve this. I'm not sure it will help but I also attempted to use the swaggerhub-maven-plugin with no luck. I got the error "illegalargumentexception: unexpected host: https://ideas-swaggerhub.myorg.com". But again clicking on the URL provided it takes me to my swaggerhub's home page.

**Comment by smizell** [comment]
@akashp1196 Try add `/v1` to your base URL without appending the slash.

```
https://ideas-swaggerhub.myorg.com/v1
```

Let us know if that works :)

**Comment by akashp1196** [comment]
@smizell Thanks for the help but sadly I get the same error but with the /v1 appended.:

› Error: request to https://ideas-swaggerhub.myorg.com/v1/apis/apatel/HubTest/1.0.1 failed, reason: unable to verify the first certificate

**Comment by smizell** [comment]
Is there a chance you're using an unsigned certificate? If so, you can use [`NODE_EXTRA_CA_CERTS`](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file) to add your certificate.

**Comment by akashp1196** [comment]
That may very well be the case. Could you perhaps give a bit more guidance on how I can get/locate the certificate. I'm assuming that referring to an SSL certificate? I haven't had to do this before.

**Comment by smizell** [comment]
> I'm assuming that referring to an SSL certificate?

Yes, SSL or TLS certificate.

> Could you perhaps give a bit more guidance on how I can get/locate the certificate.

If the certificate is the issue, you can download the SwaggerHub certificate from your browser. I'd suggest trying out a search for "download certificate from <my-browser>" as it's different for each browser. Once you have it, you can set the [`NODE_EXTRA_CA_CERTS`](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file) environment variable to point to your cert. If the cert is the problem, hopefully that will get it working.

If not, please let us know :)
