### ISSUE TITLE
Issue with swaggerhub integration:create 

### ISSUE THREAD

**Issue by sahni14** [SmartBear/swaggerhub-cli#145]
I am using an onprem version of swaggerhub.  
Trying to add a gitlab integration to my api.
I get a 404 error.

```
$ swaggerhub integration:create krnshn/testAPI12/FEATURE-InitialBuild -f gitlab_integration.json
 ›   Error: HTTP 404 Not Found
```

The swaggerhub api:get command works perfectly on the same api

```
$ swaggerhub api:get krnshn/testAPI12/FEATURE-InitialBuild
openapi: 3.0.0
info:
...
...
```

What does "Error: HTTP 404 Not Found" mean in this case? 

I am able to create the gitlab integration using the console, just not using the CLI.

I am using cli version 0.2.12
```
$ swaggerhub -v
swaggerhub-cli/0.2.12 linux-x64 node-v10.21.0
```

The swaggerhub server version is 1.25.1-56

The error handling in the CLI needs to be fixed, or we need a way to get debug logs.

Thanks

**Comment by sahni14** [comment]
Met with swaggerhub reps. They mentioned that the integrations apis are not yet available in the current version of swaggerhub onprem (as of 10/13/2020). That is why the swaggerhub integration:create  command in the CLI is not working for us.
Thanks.

**Comment by hkosova** [comment]
SwaggerHub On-Premise v. 1.26 is now available with support for `integration:create` and `api:validate`.

CLI documentation will be updated to mention On-Prem version required to use `integration:create` (PR https://github.com/SmartBear/swaggerhub-cli/pull/173).
