### ISSUE TITLE
Getting "TypeError: Cannot read property 'split' of undefined"

### ISSUE THREAD

**Issue by vthanikachalam** [SmartBear/swaggerhub-cli#182]
### Q&A
 - CLI version: [swaggerhub-cli/0.2.14]
 - OS: [Windows 10]
 - Node.js version: [node-v14.15.4]
 - SwaggerHub version if On-Premise: [SaaS / Cloud]

### Describe the bug you're encountering
When I create an API using CLI command am getting **TypeError: Cannot read property 'split'**
Command which I used is 'swaggerhub api:create AltaisHealth1/registration/1.0 --setdefault --file response.json'

### To reproduce...
1. Go to command prompt
2. Run command 'swaggerhub api:create AltaisHealth1/registration/1.0 --setdefault --file response.json'
3. See error TypeError: Cannot read property 'split' of undefined

### Expected behavior
It should not throw error

### Screenshots
![swaggerhub-cli-create-ERROR](https://user-images.githubusercontent.com/78013871/107484033-de67ff00-6ba7-11eb-9714-da247268a68a.png)
Attached the screen shot

### Additional context or thoughts
As part of enterprise automation we are planning to using swaggerhub CLI, extensively. We need your team support to fix this as early as possible

Looking forward for SmartBear/SwaggerHub Team's quick turn-around

Thanks

**Comment by barryadk** [comment]
Thanks @vthanikachalam for opening the issue. A fix for this issue has been committed and will be released this week.

**Comment by vthanikachalam** [comment]
> Thanks @vthanikachalam for opening the issue. A fix for this issue has been committed and will be released this week.

Great! Thanks @barryadk for your immediate response

**Comment by barryadk** [comment]
swaggerhub-cli version `0.2.15` was released and includes a fix for this issue.

**Comment by vthanikachalam** [comment]
Many Thanks for releasing 0.2.15, we will make use of it and provide the feedback shortly. Thanks again
