### ISSUE TITLE
swaggerhub api:update - Error: TOKEN_TYPE_INVALID

### ISSUE THREAD

**Issue by harishkulkarni-abi** [SmartBear/swaggerhub-cli#196]
We are seeing issue in the swagger hub-cli while only updating the existing API . Creating and validation are working fine . 

### Q&A (please complete the following information)
 - CLI version: [e.g. 1.0.0] swaggerhub -v
swaggerhub-cli/0.3.0 win32-x64 node-v12.16.0
 -
 - OS: windows 10 enterprise 
 - Node.js version: node -v    ---- v12.16.0
 - SwaggerHub version if On-Premise: 1.23

### Describe the bug you're encountering
We are seeing issue while only updating the existing API . Creating and validation are working fine . 
 »   Error: TOKEN_TYPE_INVALID

### To reproduce...
1. Given adding the following in .bat file 
   -----
   @echo off
set SWAGGERHUB_URL=https://swaggerhubglobal.******.com/v1
set API_KEY=<api_key.txt
set NODE_EXTRA_CA_CERTS=swg.pem
Rem certutil.exe -addstore -f "TrustedPublisher" swg.pem
set "file=api.yaml"
for /f "tokens=* delims=: " %%i in ('FINDSTR /C:"version: " %file%') do set "version=%%i"
Rem echo %version%
set version_t=%version:~9%
set version_f=%version_t:~1,-1%
Rem echo %version_f%
for /f "tokens=* delims=: " %%j in ('FINDSTR /C:"title: " %file%') do set "title=%%j"
Rem echo %title:~7%
set title=%title: =-%
echo "updating the API..!!"
call swaggerhub api:update ***_Org/%title:~7%/%version_f%  --file=api.yaml --visibility=public
echo Creating API
call swaggerhub api:create ****_Org/%title:~7%/%version_f%  --file api.yaml --visibility public
echo "Validating the API.....!!!!"
call swaggerhub api:validate ****_Org/%title:~7%/%version_f%
------
2. Execute command - run the .bat file .
3. See error: 
C:\*****\swagger-cli\swagger\swagger>validate.bat
"updating the API..!!"
 »   Error: TOKEN_TYPE_INVALID
Creating API
 »   Error: API version '*****_Org/Inventory-BAPI-1234/1.0.7' already exists in SwaggerHub
"Validating the API.....!!!!"

**Comment by barryadk** [comment]
Hi @harishkulkarni-abi, thanks for opening the issue. When updating an API, the SwaggerHub CLI first checks whether the API definition is currently set as public or private. This functionality was only made available using an API token in the SwaggerHub On-Premise 1.26 release.

Updating to the latest version of SwaggerHub On-Premise will resolve your issue. However I will investigate whether it is possible to remove this check in the CLI (when calling `api:update` with the `--file` argument). I will update you on progress as this may resolve the issue for your current version of SwaggerHub On-Prem.
