### ISSUE TITLE
Add support for projects

### ISSUE THREAD

**Issue by lorisites** [SmartBear/swaggerhub-cli#199]
**Is your feature request related to a problem? Please describe.**
We would like to use the CLI as part of our CI/CD process but we are using projects for environments and there is no support for projects in the CLI

**Describe the solution you'd like**
***Add support for projects (Support the endpoints listed for projects here:  https://app.swaggerhub.com/apis-docs/swagger-hub/registry-api/1.0.62#/ )
***Add support for listing projects that an API is in.    

**Describe alternatives you've considered**
Writing our own CLI which would be a  wrapper for the https://app.swaggerhub.com/apis-docs/swagger-hub/registry-api/1.0.62#/ endpoints

**Additional context**
![image](https://user-images.githubusercontent.com/801381/116432279-8049d000-a816-11eb-9bd6-892ef1d45096.png)

**Comment by skunisetty-equinix** [comment]
This is something that we at Equinix would need it.
We creates/upload APIs through a variety of mechanisms (not just through UI) and we use projects to create APIs for particular teams.
We need the support for 'create an API in a particular project' in CLI & also in the Swaggerhub Maven plugin.

**Comment by BohdanKaminskyi** [comment]
+1, We also need this feature so much

**Comment by nelegatti** [comment]
+1 !  We are needing this feature as well

**Comment by CalemRoelofsSB** [comment]
Hi everyone, happy to announce that this has now been added in v0.6.0 and is available from npm
