### ISSUE TITLE
api:validate should return an error when the api doesn't exist

### ISSUE THREAD

**Issue by redparham** [SmartBear/swaggerhub-cli#329]
### Q&A (please complete the following information)
 - CLI version: 0.8.0
 - OS: macOS Ventura
 - Node.js version: 20.3.1
 - SwaggerHub version if On-Premise: 2.6.0+123

### Describe the bug you're encountering
When executing api:validate for a non-existent api, an error should be returned.

### To reproduce...
1. Given 'FOO/BAR/1' doesn't exist
2. Execute command 'swaggerhub api:validate FOO/BAR/1 --fail-on-critical'
3. No error is returned and exit code is zero

### Expected behavior
Return an error message with a non-zero error code

**Comment by CalemRoelofsSB** [comment]
Hey @redparham, we are looking at this internally and will respond with a solution once it's ready.

**Comment by CalemRoelofsSB** [comment]
@redparham fix for this has been released on NPM with version 0.8.1 - https://www.npmjs.com/package/swaggerhub-cli/v/0.8.1
Thank you for your feedback and et us know if there's any encounter any further issues 😄
