### ISSUE TITLE
Default yaml version

### ISSUE THREAD

**Issue by Angel0926** [SmartBear/swaggerhub-cli#362]
HI. How i can take default yaml swagger version https://swaggerhub.organisation.com/v1/apis/company/myapi/????/swagger.yaml. 
What i can add instead of ?????

**Comment by CalemRoelofsSB** [comment]
Hi @Angel0926 are you looking do this using the CLI?

If so, using `swaggerhub api:get company/myapi` without the [VERSION] paramter as outlined in the documentation [here](https://github.com/SmartBear/swaggerhub-cli#swaggerhub-apiget) will pull the default version of the API from SwaggerHub.

**Comment by Angel0926** [comment]
@CalemRoelofsSB  i use it i this script         oasdiff breaking "canary-api/target/generated/openapi.yaml" "https://swaggerhub.company.com/v1/apis/company/myapi/0.1.0-ci.2345/swagger.yaml" --fail-on ERR and i want use latest swagger version instead of 0.1.0-ci.2345

**Comment by CalemRoelofsSB** [comment]
@Angel0926 I'm not familiar with that tool, but assuming that it lets you use local file paths, the easiest thing to do here would be to download the file using the CLI and save it locally with something like:
```shell
swaggerhub api:get company/myapi > myapi-latest.yaml
oasdiff "canary-api/target/generated/openapi.yaml"  "./myapi-latest.yaml" 
```

We don't currently have a direct link available to pull the YAML file for the default version without the version being specified, but the CLI does provide this functionality to save you trying to do this manually through CURL or something similar.

**Comment by CalemRoelofsSB** [comment]
> `swaggerhub myapi:get company/myapi > myapi-latest.yaml`

This should be `swaggerhub *api:get*` as opposed to `*myapi:get*`, refer to the above comment.

**Comment by mhiggins-SA** [comment]
SwaggerHub cli for On-premise needs /v1 on the end, the URL for SaaS is api.swaggerhub.com NOT app.swaggerhub.com.



Mise le meas
---
Micheál Higgins   |   Senior Solutions Architect
m: +353.86.235.4599
e: ***@***.******@***.***>
***@***.***<https://smartbear.com/>

smartbear.com<https://www.smartbear.com/>
***@***.***<https://www.facebook.com/smartbear>  ***@***.*** <https://www.linkedin.com/company/smartbear>   ***@***.*** <https://twitter.com/SmartBear>   ***@***.*** <https://www.youtube.com/channel/UC3iDZqrLWQZ4dh8zn2rU9hA>

**Comment by Angel0926** [comment]
i dont understant what should i write and where ?

**Comment by CalemRoelofsSB** [comment]
@Angel0926 from the looks of it you haven't configured the CLI properly for SwaggerHub On-Premise, please refer to the documentation in the README regarding `swaggerhub configure` and [Additional configuration for SwaggerHub On-Premise](https://github.com/SmartBear/swaggerhub-cli#additional-configuration-for-swaggerhub-on-premise)

**Comment by Angel0926** [comment]
@CalemRoelofsSB  hi  i  did it. thank you.but i have other question. How i can add bearer token in openapi schema?

**Comment by CalemRoelofsSB** [comment]
Hi @Angel0926, we mainly just deal with issues with the SwaggerHub CLI tool in this repo. For general questions about OpenAPI schemas and related topics, I invite you to come over to our community site at https://community.smartbear.com/t5/SwaggerHub/ct-p/SwaggerHub :)
