### ISSUE TITLE
swaggerhub api:setdefault fails with 'Input does not match the expected structure'

### ISSUE THREAD

**Issue by dobrusev** [SmartBear/swaggerhub-cli#484]
### Q&A (please complete the following information)
 - CLI version: [e.g. 1.0.0] swaggerhub-cli/0.9.0 darwin-arm64 node-v18.17.0
 - OS: [e.g. macOS Ventura]
 - Node.js version: [e.g. 18.15.0]
 - SwaggerHub version if On-Premise: [e.g. 2.3.0+111]

### To reproduce...
1. Given I have the library installed and api key configured
2. Execute command swaggerhub api:setdefault OWNER/API_NAME/[VERSION]
3. See error  Error: Input does not match the expected structure

### Expected behavior

No errors and default version is selected

**Comment by barryadk** [comment]
Thanks @dobrusev for the report. After investigation, we discovered a regression in the server-side API. A fix for the issue was deployed - could you check if you're still encountering the problem?

**Comment by dobrusev** [comment]
@barryadk It's working now, thank you for the quick fix.
